name: Build & Deploy Spring app
on: 
    push: 
   branches:
        - main 
   jobs:
   buld-deploy:
   name: build and deploy sprng boot for begnnner
   runs-on: ubuntu-latest
   steps:
   - name: Checout Code
   uses: actions/checout@v3
   - name: Setup JD 17
   uses: actions/setup-java@v3
   with: 
   distributon : 'corretto'
   java-verson:17
   -name: Unit Tests
   run: mvn -B test  --fle pom.xml
-name: Buld the applcaton 
mvn -B  package --fle pom.xml
