name: Build & Deploy Spring app
on: [push , branches[ master]] 
jobs: 
   build_deploy: 
   - name: build and deploy sprng boot for begnnner
     runs-on: ubuntu-latest
     steps:
    - name: Checkout Code
    - uses: actions/checkout@v3
   - name: Setup JD 17
       uses: actions/setup-java@v3
       with: 
       distribution : 'corretto'
   java-version: 17
   -name: Unit Tests
      run: mvn -B test  --file pom.xml
     -name: Buld the applcaton 
      run: mvn -B  package --file pom.xml
